WAITING_NEXT_ROUND = 1
INVALID_INPUT = 'Invalid option'
TRY_TIME = 3
CLS_COMMAND_WINDOWS = ['cls'] # windows
OUTPUT_TRY_TIMES = 'You type wrong option too many times. Something wrong'
OUTPUT_GAME_POINT_ERROR = "Not valid point. Game's point is not number"
WAITING_TIME_LOSE = 1
TEXT_RUNNING = 0.2
NEXT_ROUND_TIME_LOSE = 3